
server.port=2058

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/brandlocus
#spring.datasource.url=jdbc:postgresql://dev-payment-gateway-db.ckyiectzjg4x.eu-west-1.rds.amazonaws.com:5432/stg_payment_gateway_db?autoReconnect=true
spring.datasource.username=postgres
spring.datasource.password=Icui4cu2
#Not advisable in production
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.com.gateway.NowNowGateway=INFO
logging.level.org.hibernate=INFO



spring.main.banner-mode=console

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.csrf.enabled=false
springdoc.swagger-ui.enabled=true


encryption.SECRET = NowNow!234567
encryption.MODE = DES






